orbs: 
  node: circleci/node@2.0.2

version: 2.1
jobs:
  Build:
    docker:
      - image: node:16
    working_directory: ~/orange-bot
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Lint
          command: yarn run lint


workflows:
  "Orangebot deploy checklist":
    jobs:
      - Build