orbs:
  node: circleci/node@2.0.2
  slack: circleci/slack@4.0

version: 2.1

jobs:
  Build:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run jest
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: '@orangebotdevs'
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  'Orangebot deploy checklist':
    jobs:
      - Build:
          context: slack-secrets
