orbs: 
  node: circleci/node@2.0.2

version: 2.1
jobs:
  Build:
    steps:
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Lint
          command: yarn run lint


workflows:
  "Orangebot deploy checklist":
    jobs:
      - Build